FROM node:20-alpine AS builder
WORKDIR /app

COPY frontend/package.json ./package.json
RUN npm install

COPY frontend ./
RUN npm run build

FROM nginx:1.27-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY dockerfiles/nginx.frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
